/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/resorts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resorts */
        get: operations["list_resorts_resorts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resorts/{resort_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resort */
        get: operations["get_resort_resorts__resort_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resorts/{resort_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_resorts__resort_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resorts/{resort_id}/observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Observations */
        get: operations["get_observations_resorts__resort_id__observations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resorts/{resort_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_resorts__resort_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/firestore-ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Firestore Ping */
        get: operations["firestore_ping_debug_firestore_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DailyPoint */
        DailyPoint: {
            /** Date */
            date: string;
            /** Snow In */
            snow_in?: number | null;
            /** Temp Hi F */
            temp_hi_f?: number | null;
            /** Temp Lo F */
            temp_lo_f?: number | null;
            /** Wind Mph Max */
            wind_mph_max?: number | null;
        };
        /** DailySnow */
        DailySnow: {
            /** Date */
            date: string;
            /** Snow In 24H */
            snow_in_24h?: number | null;
            /** Snow Depth In */
            snow_depth_in?: number | null;
            /** Swe In */
            swe_in?: number | null;
            /** Temp Hi F */
            temp_hi_f?: number | null;
            /** Temp Lo F */
            temp_lo_f?: number | null;
            /** Source */
            source?: string | null;
        };
        /** Forecast */
        Forecast: {
            /** Resort Id */
            resort_id: string;
            /** Generated At */
            generated_at: string;
            /** Hourly */
            hourly: components["schemas"]["HourlyPoint"][];
            /** Daily */
            daily: components["schemas"]["DailyPoint"][];
            /**
             * Narrative
             * @default []
             */
            narrative: components["schemas"]["NarrativePeriod"][];
            /** Sources */
            sources: {
                [key: string]: string;
            };
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** History */
        History: {
            /** Resort Id */
            resort_id: string;
            /** Season Start */
            season_start: string;
            /** Season To Date In */
            season_to_date_in: number;
            /** Daily */
            daily: components["schemas"]["DailySnow"][];
        };
        /** HourlyPoint */
        HourlyPoint: {
            /** T */
            t: string;
            /** Temp F */
            temp_f?: number | null;
            /** Wind Mph */
            wind_mph?: number | null;
            /** Snowfall In */
            snowfall_in?: number | null;
            /** Precip In */
            precip_in?: number | null;
            /** Visibility Mi */
            visibility_mi?: number | null;
        };
        /** NarrativePeriod */
        NarrativePeriod: {
            /** Name */
            name: string;
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Temp F */
            temp_f?: number | null;
            /** Wind */
            wind?: string | null;
            /** Short */
            short: string;
            /** Detailed */
            detailed?: string | null;
            /**
             * Is Daytime
             * @default true
             */
            is_daytime: boolean;
        };
        /** Observations */
        Observations: {
            /** Resort Id */
            resort_id: string;
            snotel?: components["schemas"]["SnotelObservation"] | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /** ResortBase */
        ResortBase: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Elevation Ft */
            elevation_ft: number;
        };
        /**
         * ResortDetail
         * @description Full metadata for the detail screen.
         */
        ResortDetail: {
            /** Resort Id */
            resort_id: string;
            /** Name */
            name: string;
            /**
             * Pass
             * @enum {string}
             */
            pass: "epic" | "ikon";
            /** State */
            state: string;
            base: components["schemas"]["ResortBase"];
            summit: components["schemas"]["ResortElevation"];
            /** Snotel Triplet */
            snotel_triplet: string;
            /** Timezone */
            timezone: string;
        };
        /** ResortElevation */
        ResortElevation: {
            /** Elevation Ft */
            elevation_ft: number;
        };
        /** ResortList */
        ResortList: {
            /** Resorts */
            resorts: components["schemas"]["ResortSummary"][];
        };
        /**
         * ResortSummary
         * @description Compact row for the list screen.
         */
        ResortSummary: {
            /** Resort Id */
            resort_id: string;
            /** Name */
            name: string;
            /**
             * Pass
             * @enum {string}
             */
            pass: "epic" | "ikon";
            /** State */
            state: string;
            /** Base Elevation Ft */
            base_elevation_ft: number;
            /** Summit Elevation Ft */
            summit_elevation_ft: number;
            /** Latest Snow 24H In */
            latest_snow_24h_in?: number | null;
            /** Snow Depth In */
            snow_depth_in?: number | null;
        };
        /** SnotelObservation */
        SnotelObservation: {
            /** Station Triplet */
            station_triplet: string;
            /** Observed At */
            observed_at: string;
            /** Swe In */
            swe_in?: number | null;
            /** Snow Depth In */
            snow_depth_in?: number | null;
            /** Snow 24H In */
            snow_24h_in?: number | null;
            /** Air Temp F */
            air_temp_f?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_resorts_resorts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResortList"];
                };
            };
        };
    };
    get_resort_resorts__resort_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResortDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_forecast_resorts__resort_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Forecast"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_observations_resorts__resort_id__observations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Observations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_resorts__resort_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resort_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    firestore_ping_debug_firestore_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
